DIR_COLOR=$(tput setaf 4)
FILE_COLOR=$(tput setaf 7)

RESET=$(tput sgr0)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
BLUE=$(tput setaf 4)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
RED=$(tput setaf 1)
